version: "3.8"
services:
  gateway_service:
    build: ./gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - post_service
      - item_service
    networks:
      - mynetwork

  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  post_service:
    build: ./post_service
    ports:
      - "8002:8002"
    networks:
      - mynetwork

  item_service:
    build: ./item_service
    ports:
      - "8003:8003"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
